//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.27 at 02:32:42 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soap_server.csn.com/countries", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.csn.soap_server.countries;
